export const userConstants = {
  SET_ADD_PHOTO_DESCRIPTION: 'SET_ADD_PHOTO_DESCRIPTION',
  SET_ADD_PHOTO_FILE: 'SET_ADD_PHOTO_FILE',

  GET_USER_PROFILE_POSTS_REQUEST: 'GET_USER_PROFILE_POSTS_REQUEST',
  GET_USER_PROFILE_POSTS_SUCCESS: 'GET_USER_PROFILE_POSTS_SUCCESS',
  GET_USER_PROFILE_POSTS_FAILURE: "GET_USER_PROFILE_POSTS_FAILURE",
};