export const loginConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOG_OUT: 'LOG_OUT',

  SET_EMAIL: 'SET_EMAIL',
  SET_PASSWORD: 'SET_PASSWORD',

  SET_REGISTRATION_USERNAME: 'SET_REGISTRATION_USERNAME',
  SET_REGISTRATION_FIRST_NAME: 'SET_REGISTRATION_FIRST_NAME',
  SET_REGISTRATION_LAST_NAME: 'SET_REGISTRATION_LAST_NAME',
  SET_REGISTRATION_EMAIL: 'SET_REGISTRATION_EMAIL',
  SET_REGISTRATION_PASSWORD: 'SET_REGISTRATION_PASSWORD',
  SET_REGISTRATION_CONFIRM_PASSWORD: 'SET_REGISTRATION_CONFIRM_PASSWORD',
  SET_REGISTRATION_IMAGE: 'SET_REGISTRATION_IMAGE',


  RESET_REGISTRATION_FORM: 'RESET_REGISTRATION_FORM',
};