export const randomConstants = {
  GET_RANDOM_USER_PROFILE_POSTS_REQUEST: 'GET_RANDOM_USER_PROFILE_POSTS_REQUEST',
  GET_RANDOM_USER_PROFILE_POSTS_SUCCESS: 'GET_RANDOM_USER_PROFILE_POSTS_SUCCESS',
  GET_RANDOM_USER_PROFILE_POSTS_FAILURE: "GET_RANDOM_USER_PROFILE_POSTS_FAILURE",

    GET_RANDOM_USER_REQUEST: 'GET_RANDOM_USER_REQUEST',
    GET_RANDOM_USER_SUCCESS: 'GET_RANDOM_USER_SUCCESS',
    GET_RANDOM_USER_FAILURE: 'GET_RANDOM_USER_FAILURE',
};