export const randomConstants = {
  GET_RANDOM_USER_PROFILE_POSTS_REQUEST: 'GET_RANDOM_USER_PROFILE_POSTS_REQUEST',
  GET_RANDOM_USER_PROFILE_POSTS_SUCCESS: 'GET_RANDOM_USER_PROFILE_POSTS_SUCCESS',
  GET_RANDOM_USER_PROFILE_POSTS_FAILURE: "GET_RANDOM_USER_PROFILE_POSTS_FAILURE",

  GET_RANDOM_USER_REQUEST: 'GET_RANDOM_USER_REQUEST',
  GET_RANDOM_USER_SUCCESS: 'GET_RANDOM_USER_SUCCESS',
  GET_RANDOM_USER_FAILURE: 'GET_RANDOM_USER_FAILURE',

  CLEAR_USER_INF: 'CLEAR_USER_INF',

  SET_ADD_PHOTO_DESCRIPTION: 'SET_ADD_PHOTO_DESCRIPTION',
  SET_ADD_PHOTO_FILE: 'SET_ADD_PHOTO_FILE',
    SET_CATEGORY: 'SET_CATEGORY',

  GET_USER_PROFILE_POSTS_REQUEST: 'GET_USER_PROFILE_POSTS_REQUEST',
  GET_USER_PROFILE_POSTS_SUCCESS: 'GET_USER_PROFILE_POSTS_SUCCESS',
  GET_USER_PROFILE_POSTS_FAILURE: "GET_USER_PROFILE_POSTS_FAILURE",


  GET_FOLLOWING_REQUEST: 'GET_FOLLOWING_REQUEST',
  GET_FOLLOWING_SUCCESS: 'GET_FOLLOWING_SUCCESS',
  GET_FOLLOWING_FAILURE: 'GET_FOLLOWING_FAILURE',

  GET_FOLLOWERS_REQUEST: 'GET_FOLLOWERS_REQUEST',
  GET_FOLLOWERS_SUCCESS: 'GET_FOLLOWERS_SUCCESS',
  GET_FOLLOWERS_FAILURE: 'GET_FOLLOWERS_FAILURE',
};