export const randomConstants = {
  GET_RANDOM_USER_PROFILE_POSTS_REQUEST: 'GET_RANDOM_USER_PROFILE_POSTS_REQUEST',
  GET_RANDOM_USER_PROFILE_POSTS_SUCCESS: 'GET_RANDOM_USER_PROFILE_POSTS_SUCCESS',
  GET_RANDOM_USER_PROFILE_POSTS_FAILURE: "GET_RANDOM_USER_PROFILE_POSTS_FAILURE",

  GET_RANDOM_USER_REQUEST: 'GET_RANDOM_USER_REQUEST',
  GET_RANDOM_USER_SUCCESS: 'GET_RANDOM_USER_SUCCESS',
  GET_RANDOM_USER_FAILURE: 'GET_RANDOM_USER_FAILURE',

  CLEAR_USER_INF: 'CLEAR_USER_INF',

    SET_ADD_PHOTO_DESCRIPTION: 'SET_ADD_PHOTO_DESCRIPTION',
    SET_ADD_PHOTO_FILE: 'SET_ADD_PHOTO_FILE',

    GET_USER_PROFILE_POSTS_REQUEST: 'GET_USER_PROFILE_POSTS_REQUEST',
    GET_USER_PROFILE_POSTS_SUCCESS: 'GET_USER_PROFILE_POSTS_SUCCESS',
    GET_USER_PROFILE_POSTS_FAILURE: "GET_USER_PROFILE_POSTS_FAILURE",
};