export const filteredConstants = {
  GET_FILTERED_PHOTOS_REQUEST: 'GET_FILTERED_PHOTOS_REQUEST',
  GET_FILTERED_PHOTOS_SUCCESS: 'GET_FILTERED_PHOTOS_SUCCESS',
  GET_FILTERED_PHOTOS_FAILURE: 'GET_FILTERED_PHOTOS_FAILURE',

  GET_FILTERED_BY_COUNTRY_REQUEST: 'GET_FILTERED_BY_COUNTRY_REQUEST',
  GET_FILTERED_BY_COUNTRY_SUCCESS: 'GET_FILTERED_BY_COUNTRY_SUCCESS',
  GET_FILTERED_BY_COUNTRY_FAILURE: 'GET_FILTERED_BY_COUNTRY_FAILURE',
};