export const singleConstants = {
  GET_POST_COMMENTS_REQUEST: 'GET_POST_COMMENTS_REQUEST',
  GET_POST_COMMENTS_SUCCESS: 'GET_POST_COMMENTS_SUCCESS',
  GET_POST_COMMENTS_FAILURE: 'GET_POST_COMMENTS_FAILURE',
};