export const singleConstants = {
  GET_POST_COMMENTS_REQUEST: 'GET_POST_COMMENTS_REQUEST',
  GET_POST_COMMENTS_SUCCESS: 'GET_POST_COMMENTS_SUCCESS',
  GET_POST_COMMENTS_FAILURE: 'GET_POST_COMMENTS_FAILURE',

  GET_ONE_POST_REQUEST: 'GET_ONE_POST_REQUEST',
  GET_ONE_POST_SUCCESS: 'GET_ONE_POST_SUCCESS',
  GET_ONE_POST_FAILURE: 'GET_ONE_POST_FAILURE',

    SET_COMMENT_TEXT: 'SET_COMMENT_TEXT',
    RESET_COMMENT_TEXT: 'RESET_COMMENT_TEXT',
};